# 模糊抓取订阅链接
# clash格式订阅链接
#- type: clash
#  options:
#    url: https://raw.githubusercontent.com/aiboboxx/clashfree/refs/heads/main/clash.yml

- type: clash
  options:
    url: https://clashgithub.com/wp-content/uploads/rss/20060102.yml
    dateFormat: true